# Generated by Django 5.0.4 on 2024-04-17 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateApiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_beehive', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('specie', models.CharField(max_length=100)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apiary')),
            ],
        ),
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apiary')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apiary')),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beehive')),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beekeeper')),
            ],
        ),
    ]
