# Generated by Django 5.0.4 on 2024-04-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_apiary_beehive_beekeeper_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateApiary',
            new_name='Apiary',
        ),
    ]
